import {readFile, writeFile} from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const d = JSON.parse(await readFile(new URL('data/resume.json',root),'utf8'));
const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link = (url,label,cls='') => `<a class="${cls}" href="${esc(url)}">${esc(label)}</a>`;
const heading = (n,label,title) => `<div class="section-heading"><p class="eyebrow">${n} / ${label}</p><h2>${title}</h2></div>`;
const social = () => link(d.github,'GitHub ↗')+link(d.linkedin,'LinkedIn ↗');
const download = () => `<a class="button secondary" href="${esc(d.pdf)}" download>Download resume ↓</a>`;
const navItems = ['About','Experience','Skills','Projects',...(d.certifications.length?['Certifications']:[]),'Education','Contact'];
let profilePortrait = '';
try {
  await readFile(new URL('portrait.jpg', root));
  profilePortrait = `<img class="profile-portrait" src="portrait.jpg" alt="Portrait of ${esc(d.name)}" width="1448" height="1086" decoding="async">`;
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
}
const sections = {
nav:`<header class="header wrap"><a class="wordmark" href="#" aria-label="${esc(d.name)} home">${esc(d.name)}<span>.</span></a><button class="menu-toggle" type="button" aria-controls="main-nav" aria-expanded="false" hidden>Menu ☰</button><nav id="main-nav" aria-label="Main navigation">${navItems.map(x=>link('#'+x.toLowerCase(),x)).join('')}</nav><div class="header-actions">${link(d.pdf,'Resume ↓','nav-download')}<button id="theme-toggle" class="theme-toggle" type="button" aria-pressed="false" hidden>Dark theme</button></div></header>`,
hero:`<section class="hero wrap" aria-labelledby="intro"><div class="hero-copy"><p class="eyebrow"><span class="dot"></span>${esc(d.role)} / ${esc(d.specialization)}</p><h1 id="intro">${esc(d.name)}<span>${d.headline.map(esc).join('<br>')}</span></h1><p class="intro">${esc(d.summary)}</p><div class="actions">${link('#experience','View experience ↗','button primary')}${link('#projects','View projects','button secondary')}${download()}${link('#contact','Contact me','button secondary')}</div><div class="social">${social()}${link('mailto:'+d.email,'Email ↗')}</div></div><aside class="profile-card" aria-label="Professional overview"><div class="card-top"><span>FULL STACK DEVELOPMENT</span><span>↗</span></div>${profilePortrait}<div class="monogram" aria-hidden="true">${esc(d.name)}</div><p class="card-role">${esc(d.role)}</p><p class="card-sub">From application development to production support.</p>${d.skills.slice(0,3).map((s,i)=>`<div class="stack-row"><span>0${i+1} / ${esc(s.title)}</span><strong>${esc(s.description.split(' · ').slice(0,3).join(' · '))}</strong></div>`).join('')}<div class="card-bottom"><span>${esc(d.experience)} experience</span><span>${esc(d.location)}</span></div></aside></section>`,
about:`<section id="about" class="about wrap section"><p class="eyebrow">01 / ABOUT</p><div><h2>Built for the full lifecycle.</h2><ul class="summary-list">${d.about.map(p=>`<li>${esc(p)}</li>`).join('')}</ul></div></section>`,
experience:`<section id="experience" class="wrap section">${heading('02','EXPERIENCE','Where I’ve contributed.')}<div class="timeline">${d.experienceItems.map(j=>`<article class="job${j.current?' current-job':''}"><div class="job-meta">${j.current?'<span class="pill">CURRENT</span>':''}<p>${esc(j.period)}</p><p>${esc(j.location)}</p></div><div><h3>${esc(j.role)}</h3><p class="company">${esc(j.company)}</p><ul>${j.bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul></div></article>`).join('')}</div></section>`,
skills:`<section id="skills" class="skills-section"><div class="wrap">${heading('03','SKILLS & EXPERTISE','The tools behind the work.')}<div class="skill-filters" role="group" aria-label="Filter skills" hidden>${[['all','All skills'],['application','Application development'],['delivery','Cloud & delivery']].map(([v,l])=>`<button type="button" data-filter="${v}" aria-pressed="${v==='all'}">${esc(l)}</button>`).join('')}</div><p id="skill-status" class="sr-only" role="status"></p><div class="skills-grid">${d.skills.map((s,i)=>`<article data-category="${esc(s.category)}"><span class="skill-number">0${i+1}</span><h3>${esc(s.title)}</h3><p>${esc(s.description)}</p></article>`).join('')}</div></div></section>`,
projects:`<section id="projects" class="wrap section">${heading('04','SELECTED WORK','Infrastructure, defined in code.')}${d.projects.map((p,i)=>`<article class="project"><div><p class="eyebrow">${esc(p.type)}</p><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="tags">${p.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="actions">${link(p.url,'View source ↗','button primary')}</div></div><div class="project-details">${[['Objective',p.problem],['Solution',p.solution],['Deliverable',p.outcome]].map(([l,v])=>`<div><span>${l.toUpperCase()}</span><p>${esc(v)}</p></div>`).join('')}<details class="case-study"><summary>Explore implementation</summary><h4>Provisioning flow</h4><ol>${p.architecture.map(a=>`<li>${esc(a)}</li>`).join('')}</ol><p>${esc(p.scope)}</p></details></div></article>`).join('')}</section>`,
certifications:d.certifications.length?`<section id="certifications" class="wrap section">${heading('05','CERTIFICATIONS','Professional credentials.')}<div class="skills-grid">${d.certifications.map(c=>`<article><h3>${esc(c.name)}</h3><p>${esc(c.issuer)} · ${esc(c.year)}</p>${c.url?link(c.url,'View credential ↗'):''}</article>`).join('')}</div></section>`:'',
education:`<section id="education" class="wrap section education"><p class="eyebrow">05 / EDUCATION</p><div>${d.education.map(e=>`<article><span>${esc(e.period)}</span><h3>${esc(e.degree)}</h3><p>${esc(e.institution)}</p></article>`).join('')}</div></section>`,
contact:`<section id="contact" class="contact"><div class="wrap"><p class="eyebrow">06 / GET IN TOUCH</p><h2>Let’s build<br>something useful.</h2><p>Interested in working together or discussing an opportunity? Let’s connect.</p><a class="email" href="mailto:${esc(d.email)}">${esc(d.email)} ↗</a><div class="copy-email-row"><button id="copy-email" type="button" hidden>Copy email address</button><span id="copy-status" role="status"></span></div><div class="contact-links">${link('tel:'+d.phone.replace(/\s/g,''),d.phone)}${social()}${link(d.pdf,'Resume PDF ↓')}<span>${esc(d.location)}</span></div></div></section>`,
footer:`<footer class="wrap"><span>${esc(d.name)}</span><span>${esc(d.role)} · ${esc(d.specialization)}</span>${link('#','Back to top ↑')}</footer>`
};
const title = `${d.name} | ${d.specialization} ${d.role}`;
const schema = {'@context':'https://schema.org','@type':'Person',name:d.name,jobTitle:d.role,url:d.site,sameAs:[d.github,d.linkedin],knowsAbout:d.skills.map(s=>s.title)};
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(d.summary)}"><meta name="theme-color" content="#182c28"><link rel="canonical" href="${esc(d.site)}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(d.summary)}"><meta property="og:url" content="${esc(d.site)}"><meta property="og:image" content="${esc(d.site)}social-card.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="${esc(d.name)} — ${esc(d.specialization)}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="polish.css"><link rel="stylesheet" href="portfolio.css"><script src="interactions.js" defer></script><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body><a class="skip" href="#main">Skip to content</a>${sections.nav}<main id="main">${['hero','about','experience','skills','projects','certifications','education','contact'].map(k=>sections[k]).join('')}</main>${sections.footer}</body></html>`;
await writeFile(new URL('index.html',root),html);
await writeFile(new URL('sitemap.xml',root),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${esc(d.site)}</loc></url></urlset>`);
await writeFile(new URL('robots.txt',root),`User-agent: *\nAllow: /\nSitemap: ${d.site}sitemap.xml\n`);
// Social image source is rendered to PNG using a browser, not generated artwork.
await writeFile(new URL('social-card.html',root),`<!doctype html><html lang="en"><meta charset="utf-8"><title>Social preview</title><style>*{box-sizing:border-box}body{margin:0;width:1200px;height:630px;padding:75px;background:#182c28;color:#f6f5ef;font-family:Arial,sans-serif}p{font-size:22px;color:#d9f078;letter-spacing:3px}h1{font-size:78px;margin:65px 0 20px}h2{font-size:35px;font-weight:400}footer{border-top:1px solid #59705e;margin-top:65px;padding-top:25px;font-size:20px;color:#bccbbb}</style><p>PROFESSIONAL PORTFOLIO</p><h1>${esc(d.name)}</h1><h2>${esc(d.role)} / ${esc(d.specialization)}</h2><footer>${esc(d.experience)} experience · ${esc(d.location)}</footer></html>`);
console.log('Built static portfolio from data/resume.json');
